services:
  appointments-db:
    container_name: clinic-appointments-db
    image: postgres:15-alpine
    restart: always
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db-data-appointments:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clinic-network
      
  clinic-appointments-ms:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /home/node/app
    container_name: clinic-appointments-ms
    env_file: 
      - .env
    depends_on:
      appointments-db:
        condition: service_healthy
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - .:/home/node/app
    command: >
      sh -c "
        echo '🔄 Esperando banco ficar disponível...' &&
        /wait-for-it.sh appointments-db:5432 --strict --timeout=60 &&
        echo '🚀 Rodando migrations...' &&
        npm run typeorm migration:run && 
        echo '✅ Iniciando app...' &&
        npm run dev
      "
    networks:
      - clinic-network

volumes:
  db-data-appointments:
   
networks:
  clinic-network:
   external: true